### ISSUE TITLE
Order ne fonctionne pas

### ISSUE THREAD

**Issue by brospars** [a-grasso-dev/projet_5#1]
Quand tu crées la variable `contact` : les valeurs de `userName`, `userSurname`, etc n'ont jamais été mis à jour :

https://github.com/a-grasso-dev/projet_5/blob/f907592d6fd2f9f53ff54eab0131f954cb56e1ad/panier.js#L210-L216

Ici par exemple quand tu vérifies la valeur, tu mets à jour le localStorage mais pas la variable `userEmail` :

https://github.com/a-grasso-dev/projet_5/blob/f907592d6fd2f9f53ff54eab0131f954cb56e1ad/panier.js#L169-L173

Enfin les variables `contact` et `order` devrait être définit dans la fonction sendOrder pour être sur d'avoir les dernières valeurs (sinon elles sont crées uniquement au chargement de la page)

**Comment by a-grasso-dev** [comment]
Bah oui! c'est pour cela que ça ne fonctionnez pas! merci @brospars !
