### ISSUE TITLE
Factoriser la verification des infos du formulaire

### ISSUE THREAD

**Issue by brospars** [a-grasso-dev/projet_5#2]
Tout ce code est très répétitif, je te conseille de faire une fonction de validation que tu réutilises plutot que de faire 5 fois la même chose.

https://github.com/a-grasso-dev/projet_5/blob/f907592d6fd2f9f53ff54eab0131f954cb56e1ad/panier.js#L69-L192

par exemple : 

```js
// tu déclares une fonction de validation
const validForm = (id, regex, valeur) => {
    // tu reprends ton code ici
}

// Puis tu l'utilise pour chaque élément du formulaire
name.addEventListener("input", function (e) {
    validForm('name', regName, name.value)
});
```

**Comment by a-grasso-dev** [comment]
merci @brospars pour tes conseils! toujours le n 1!
